---
apiVersion: v1
kind: Service
metadata:
  name: mehmoodreactapp
spec:
   ports:
     - port: 80
       nodePort: 30000
       targetPort: mehmoodapp-port
       protocol: TCP
   selector: 
        app: mehmoodapp
   type: NodePort

